# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-28 00:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20170527_2040'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainVisual',
        ),
    ]
