# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-28 01:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_delete_mainvisual'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='employment_satus',
            field=models.CharField(choices=[('Student', 'Student'), ('Employed', 'Employed')], default=datetime.datetime(2017, 5, 28, 1, 26, 37, 328657, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
